#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config/qBittorrent \
	/config/data

# copy config
[[ ! -e /config/qBittorrent/qBittorrent.conf ]] && \
	cp /defaults/qBittorrent.conf /config/qBittorrent/qBittorrent.conf

# initialize openpyn
/openpyn/openpyn_init.exp

# permissions
chown -R abc:abc \
	/config
